services:

    nc-db:
        image: mariadb:10.11.2
        command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
        env_file: homeserver.env
        volumes:
            - ncdb:/var/lib/mysql
        networks:
            - private
        restart: always
        secrets:
            - mysql_user
            - mysql_password
            - mysql_database
            - mysql_root_password

    redis:
        image: redis:7-bullseye
        restart: always
        networks:
            - private

    nc-app:
        image: nextcloud:25-apache
        env_file: homeserver.env
        volumes:
            - ncdata:/var/www/html
        ports:
            - 80:80
        networks:
            - private
            - ondisplay
        links:
            - nc-db
            - redis
        restart: always
        depends_on:
            - nc-db
            - redis
        secrets:
            - mysql_user
            - mysql_password
            - mysql_database
            - nextcloud_admin_user
            - nextcloud_admin_password

networks:
    private:
        internal: true
    ondisplay:

volumes:
    ncdata:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /tank/nc/data
    ncdb:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /tank/nc/db

secrets:
    mysql_user:
        file: mysql_user.secret
    mysql_password:
        file: mysql_password.secret
    mysql_database:
        file: mysql_database.secret
    mysql_root_password:
        file: mysql_root_password.secret
    nextcloud_admin_user:
        file: nextcloud_admin_user.secret
    nextcloud_admin_password:
        file: nextcloud_admin_password.secret