services:

    NCDatabase:
        image: mariadb:10.11.2

        env_file: homeserver.env
        
        volumes: 
            - type: bind
              source: /tank/NC/NCDB
              target: /var/lib/mysql

        networks:
            - private

        environment:
            - MYSQL_USER_FILE
            - MYSQL_PASSWORD_FILE
            - MYSQL_DATABASE_FILE
            - MYSQL_ROOT_PASSWORD_FILE

        restart: always

        secrets:
            - mysql_user
            - mysql_password
            - mysql_database
            - mysql_root_password

    NCFrontend:
        image: nextcloud:23-apache

        env_file: homeserver.env
        
        volumes: 
            - type: bind
              source: /tank/NC/NCData
              target: /var/www/html

        ports:
          - 8080:80

        networks:
            - private
            - ondisplay

        links:
            - NCDatabase

        environment:
            - MYSQL_HOST
            - MYSQL_USER_FILE
            - MYSQL_PASSWORD_FILE
            - MYSQL_DATABASE_FILE
            - NEXTCLOUD_ADMIN_USER_FILE
            - NEXTCLOUD_ADMIN_PASSWORD_FILE

        restart: always

        depends_on:
            - NCDatabase

        secrets:
            - mysql_user
            - mysql_password
            - mysql_database
            - nextcloud_admin_user
            - nextcloud_admin_password

networks:
    private:
        internal: true
    ondisplay:

secrets:
    mysql_user:
        file: mysql_user.secret
    mysql_password:
        file: mysql_password.secret
    mysql_database:
        file: mysql_database.secret
    mysql_root_password:
        file: mysql_root_password.secret
    nextcloud_admin_user:
        file: nextcloud_admin_user.secret
    nextcloud_admin_password:
        file: nextcloud_admin_password.secret
