x-nc-app: &nc-app
    image: nextcloud:25-apache
    volumes:
        - ncdata:/var/www/html
    networks:
        - private
        - ondisplay
    links:
        - nc-db
        - redis
    restart: unless-stopped
    depends_on:
        - nc-db
        - redis
    env_file: homeserver.env
    environment:
        - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
        - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
        - MYSQL_DATABASE_FILE=/run/secrets/mysql_database
        - MYSQL_USER_FILE=/run/secrets/mysql_user
        - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
        - MYSQL_HOST=nc-db
        - REDIS_HOST=redis
    secrets:
        - mysql_user
        - mysql_password
        - mysql_database
        - nextcloud_admin_user
        - nextcloud_admin_password

services:

    nc-db:
        image: mariadb:10.11.2
        command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
        volumes:
            - ncdb:/var/lib/mysql
            - ./mariadb_override.cnf:/etc/mysql/conf.d/override.cnf:ro
        networks:
            - private
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
            - MYSQL_DATABASE_FILE=/run/secrets/mysql_database
            - MYSQL_USER_FILE=/run/secrets/mysql_user
            - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
            - MARIADB_AUTO_UPGRADE=1
            - MARIADB_DISABLE_UPGRADE_BACKUP=1
        secrets:
            - mysql_user
            - mysql_password
            - mysql_database
            - mysql_root_password

    redis:
        image: redis:7-bullseye
        restart: unless-stopped
        networks:
            - private

    nc-app:
        <<: *nc-app
        ports:
            - 80:80

    nc-cron:
        <<: *nc-app
        entrypoint: /cron.sh
        depends_on:
            - nc-app

networks:
    private:
        internal: true
    ondisplay:

volumes:
    ncdata:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /tank/nextcloud
    ncdb:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /tank/mariadb

secrets:
    mysql_user:
        file: mysql_user.secret
    mysql_password:
        file: mysql_password.secret
    mysql_database:
        file: mysql_database.secret
    mysql_root_password:
        file: mysql_root_password.secret
    nextcloud_admin_user:
        file: nextcloud_admin_user.secret
    nextcloud_admin_password:
        file: nextcloud_admin_password.secret
