x-nc-app: &nc-app
    image: nextcloud:25-apache
    volumes:
        - ncdata:/var/www/html
    networks:
        - internal-only
        - exposed
    restart: unless-stopped
    links:
        - caddy
        - redis
        - nc-db
    depends_on:
        - nc-db
        - redis
    environment:
        - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
        - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
        - NEXTCLOUD_TRUSTED_DOMAINS=${MY_DOMAIN}
        - NEXTCLOUD_TRUSTED_PROXIES=caddy
        - OVERWRITECLIURL=https://${MY_DOMAIN}
        - OVERWRITEPROTOCOL=https
        - MYSQL_DATABASE_FILE=/run/secrets/mysql_database
        - MYSQL_USER_FILE=/run/secrets/mysql_user
        - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
        - MYSQL_HOST=nc-db
        - REDIS_HOST=redis
    secrets:
        - mysql_user
        - mysql_password
        - mysql_database
        - nextcloud_admin_user
        - nextcloud_admin_password

services:

    nc-db:
        container_name: nc-db
        image: mariadb:10.11.2
        command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
        volumes:
            - ncdb:/var/lib/mysql
        networks:
            - internal-only
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
            - MYSQL_DATABASE_FILE=/run/secrets/mysql_database
            - MYSQL_USER_FILE=/run/secrets/mysql_user
            - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
            - MARIADB_AUTO_UPGRADE=1
            - MARIADB_DISABLE_UPGRADE_BACKUP=1
        configs:
            - source: mariadb-override
              target: /etc/mysql/conf.d/override.cnf
        secrets:
            - mysql_user
            - mysql_password
            - mysql_database
            - mysql_root_password

    redis:
        container_name: redis
        image: redis:7-bullseye
        restart: unless-stopped
        networks:
            - internal-only

    nc-app:
        container_name: nc-app
        <<: *nc-app
        labels:
            caddy: "${MY_DOMAIN}"
            caddy.reverse_proxy: "{{upstreams 80}}"
            caddy.file_server: ""
            caddy.encode: gzip
            caddy.header: /*
            caddy.header.Strict-Transport-Security: '"max-age=15552000;"'
            caddy.redir_0: "/.well-known/carddav /remote.php/dav"
            caddy.redir_1: "/.well-known/caldav /remote.php/dav"
            caddy.@forbidden.path: "/.htaccess /data/* /config/* /db_structure /.xml /README /3rdparty/* /lib/* /templates/* /occ /console.php"
            caddy.respond: "@forbidden 403"

    nc-cron:
        container_name: nc-cron
        <<: *nc-app
        entrypoint: /cron.sh
        depends_on:
            - nc-app

    caddy:
        container_name: caddy
        image: lucaslorentz/caddy-docker-proxy:2.8
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        networks:
            - exposed
            - internal-only
        environment:
            - CADDY_INGRESS_NETWORKS=internal-only
        depends_on:
            - nc-app
            - nc-cron
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - caddy-data:/data
            - ncdata:/nextcloud/var/www/html:ro

networks:
    internal-only:
        name: internal-only
        internal: true
    exposed:
        name: exposed

volumes:
    ncdata:
        name: ncdata
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /tank/nextcloud
    ncdb:
        name: ncdb
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /tank/mariadb
    caddy-data:
        name: caddy-data

configs:
    mariadb-override:
        file: ./mariadb_override.cnf

secrets:
    mysql_user:
        file: mysql_user.secret
    mysql_password:
        file: mysql_password.secret
    mysql_database:
        file: mysql_database.secret
    mysql_root_password:
        file: mysql_root_password.secret
    nextcloud_admin_user:
        file: nextcloud_admin_user.secret
    nextcloud_admin_password:
        file: nextcloud_admin_password.secret
