services:

    db:
        image: mariadb:10.11.2
        command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
        env_file: homeserver.env
        volumes: 
            - type: bind
              source: /tank/nc/db
              target: /var/lib/mysql
        networks:
            - private
        restart: always
        secrets:
            - mysql_user
            - mysql_password
            - mysql_database
            - mysql_root_password

    redis:
        image: redis:7-bullseye
        restart: always
        networks:
            - private

    app:
        image: nextcloud:25-apache
        env_file: homeserver.env
        volumes: 
            - type: bind
              source: /tank/nc/ncdata
              target: /var/www/html
        ports:
          - 8080:80
        networks:
            - private
            - ondisplay
        links:
            - db
            - redis
        restart: always
        depends_on:
            - db
            - redis
        secrets:
            - mysql_user
            - mysql_password
            - mysql_database
            - nextcloud_admin_user
            - nextcloud_admin_password

networks:
    private:
        internal: true
    ondisplay:

secrets:
    mysql_user:
        file: mysql_user.secret
    mysql_password:
        file: mysql_password.secret
    mysql_database:
        file: mysql_database.secret
    mysql_root_password:
        file: mysql_root_password.secret
    nextcloud_admin_user:
        file: nextcloud_admin_user.secret
    nextcloud_admin_password:
        file: nextcloud_admin_password.secret
