version: "3.7"

services:

    NCDatabase:
        image: "mariadb:10.11.2"
        
        volumes:
            - "NCDB:/var/lib/mysql"

        environment:
            - MYSQL_USER_FILE
            - MYSQL_PASSWORD_FILE
            - MYSQL_DATABASE_FILE
            - MYSQL_ROOT_PASSWORD_FILE

        restart: "always"

        secrets:
            - mysql_user
            - mysql_password
            - mysql_database
            - mysql_root_password

        networks: ["common"]


    NCFrontend:
        image: "nextcloud:23-apache"

        volumes: 
          - "NCData:/var/www/html"

        environment:
            - MYSQL_HOST
            - MYSQL_USER_FILE
            - MYSQL_PASSWORD_FILE
            - MYSQL_DATABASE_FILE
            - NEXTCLOUD_ADMIN_USER_FILE
            - NEXTCLOUD_ADMIN_PASSWORD_FILE

        restart: "always"

        depends_on:
            - "NCDatabase"

        secrets:
            - mysql_user
            - mysql_password
            - mysql_database
            - nextcloud_admin_user
            - nextcloud_admin_password

        networks: ["net", "common"]

volumes:
    NCDB: /tank/NC/NCDB
    NCData: /tank/NC/NCData

networks:
    net:
        external: true
    common:
        internal: true

secrets:
    mysql_user:
        file: mysql_user.secret
    mysql_password:
        file: mysql_password.secret
    mysql_database:
        file: mysql_database.secret
    mysql_root_password:
        file: mysql_root_password.secret
    nextcloud_admin_user:
        file: nextcloud_admin_user.secret
    nextcloud_admin_password:
        file: nextcloud_admin_password.secret
