version: "3.7"

services:

    NCDatabase:
        image: "mariadb:10.11.2"
        
        volumes:
            - "NCDB:/var/lib/mysql"

        environment:
            - MYSQL_ROOT_PASSWORD_FILE
            - MYSQL_DATABASE_FILE
            - MYSQL_USER_FILE
            - MYSQL_PASSWORD_FILE

        restart: "on-failure"
        networks: ["common"]

    NCFrontend:
        image: "nextcloud:23-apache"

        volumes: 
          - "NCData:/var/www/html"

        environment:
            - MYSQL_HOST
            - MYSQL_DATABASE_FILE
            - MYSQL_USER_FILE
            - MYSQL_PASSWORD_FILE
            - NEXTCLOUD_ADMIN_USER_FILE
            - NEXTCLOUD_ADMIN_PASSWORD_FILE

        depends_on:
            - "NCDatabase"
        networks: ["net", "common"]

volumes:
    NCDB: /tank/NC/NCDB
    NCData: /tank/NC/NCData

networks:
    net:
        external: true
    common:
        internal: true
