- name: Server setup
  hosts: myservers
  become: true
  tasks:
    - name: Allow memory over commit
      ansible.posix.sysctl:
        name: vm.overcommit_memory
        value: "1"
    - name: Install required things
      block:
        - name: Add contrib and backports repositories
          ansible.builtin.apt_repository:
            repo: "{{ item }}"
          loop:
            - "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib"
            - "deb-src http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib"
        - name: Install Linux Headers and update cache
          ansible.builtin.apt:
            name:
              - linux-headers-amd64
            update_cache: true
        - name: Install zfs and docker
          ansible.builtin.apt:
            update_cache: false
            name:
              - docker
              - docker-compose
              - zfsutils-linux
              - zfs-dkms
    - name: Find Drive configuration and check for pre-existing ZFS pools
      block:
        - name: Get the boot drive
          ansible.builtin.shell: df /boot | tail -1 | awk '{print $1}' | sed 's/[0-9]*$//'
          register: boot_drive
          changed_when: false
        - name: Get a list of drives that are not the boot drive
          ansible.builtin.shell: lsblk -dpn -I 8 -o NAME -l | sed "\&{{ boot_drive.stdout | quote }}&d"
          register: zpool_drives
          changed_when: false
        - ansible.builtin.fail:
            msg: No additional drives were found on the system for ZFS use.
          when: zpool_drives.stdout_lines|length==0
        - name: Check existence of zpools on drives
          ansible.builtin.shell: zpool import -N -d {{ zpool_drives.stdout_lines | join(" -d ") }}
          register: zpool_import_results
          changed_when: false