- name: Server setup
  hosts: myservers
  become: true
  tasks:
    - name: Allow memory over commit
      ansible.posix.sysctl:
        name: vm.overcommit_memory
        value: "1"
    - name: Add contrib and backports repositories
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
      loop:
        - "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib"
        - "deb-src http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib"
    - name: Install Linux Headers
      ansible.builtin.apt:
        name: "linux-headers-amd64"
        update_cache: true
    - name: Install ZFS
      ansible.builtin.apt:
        name: "zfsutils-linux"
        update_cache: true
        default_release: "{{ ansible_distribution_release }}-backports"