- name: Server setup
  hosts: myservers
  become: true
  vars:
    zpool_name: tank
    dataset_nextcloud_name: nextcloud
    dataset_nextcloud_options:
      - compression=lz4
    dataset_db_name: mariadb
    dataset_db_options:
      - recordsize=16k
      - primarycache=metadata
      - compression=lz4
      - logbias=throughput
      - atime=off
  tasks:
    - name: Allow memory over commit
      ansible.posix.sysctl:
        name: vm.overcommit_memory
        value: "1"
    - name: Install required things
      block:
        - name: Add contrib and backports repositories
          ansible.builtin.apt_repository:
            repo: "{{ item }}"
          loop:
            - "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib"
            - "deb-src http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib"
        - name: Install Linux Headers and update cache
          ansible.builtin.apt:
            name:
              - linux-headers-amd64
            update_cache: true
        - name: Install zfs and docker
          ansible.builtin.apt:
            update_cache: false
            name:
              - docker
              - docker-compose
              - zfsutils-linux
              - zfs-dkms
    - name : Get zfs to mount everything it knows about
      ansible.builtin.shell: zfs mount -a
      changed_when: false
      ignore_errors: true
    - name: Check existence of zpool
      ansible.builtin.command: zpool list -t filesystem -H -o name
      register: existing_zpools
      changed_when: false
    - name: Unknown zpool found
      ansible.builtin.fail:
        msg: "Existing zpool(s) found with name(s): {{ existing_zpools.stdout_lines | join(', ') }}"
      when: existing_zpools.stdout != "" and existing_zpools.stdout != zpool_name
    - name: Import or create zpool
      block:
      - name: Import zpool
        ansible.builtin.command: zpool import {{ zpool_name }}
        register: zpool_import_results
        changed_when: false
        ignore_errors: true
      - name: Create zpool
        block:
          - name: Get the boot drive
            ansible.builtin.shell: df /boot | tail -1 | awk '{print $1}' | sed 's/[0-9]*$//'
            register: boot_drive
            changed_when: false
          - name: Get a list of drives that are not the boot drive
            ansible.builtin.shell: lsblk -dpn -I 8 -o NAME -l | sed "\&{{ boot_drive.stdout | quote }}&d"
            register: zpool_drives
            changed_when: false
          - name: Create zpool
            ansible.builtin.command: zpool create -o ashift=12 {{ zpool_name }} raidz2 {{ zpool_drives.stdout_lines | join(' ') }}
        when: zpool_import_results.rc != 0
      when: existing_zpools.stdout != zpool_name
    - name: Check existence of dataset
      ansible.builtin.command: zfs list -t volume -H -o name
      register: existing_datasets
      changed_when: false