- name: Server setup
  hosts: myservers
  become: true
  tasks:
    - name: Allow memory over commit
      ansible.posix.sysctl:
        name: vm.overcommit_memory
        value: "1"
    - name: Add contrib and backports repositories
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
      loop:
        - "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib"
        - "deb-src http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib"
    - name: Install Linux Headers and update cache
      ansible.builtin.apt:
        name:
          - linux-headers-amd64
        update_cache: true
    - name: Install zfs utils and zfs kernal stuff in that order
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: false
        loop:
          - zfsutils-linux
          - zfs-dkms
    - name: Install docker and docker-compose
      ansible.builtin.apt:
        name: 
          - docker
          - docker-compose
        update_cache: false
    - name: Get the boot drive
      command: df /boot | tail -1 | awk '{print $1}' | sed 's/[0-9]*$//'
      register: boot_drive
      changed_when: false
    - name: Get a list of drives that are not the boot drive
      command: lsblk -dpn -I 8 -o NAME -l | sed "\&{{ boot_drive }}&d"
      register: zpool_drives
      changed_when: false
    - name: Check existence of zpools on drives
      command: "{{ 'zpool import -N ' + ' -d'.join(zpool_drives)}}"
      register: zpool_import_results
      changed_when: false
