services:
  grafana:
    image: grafana/grafana-enterprise:10.0.1
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - caddy
    environment:
      - GF_SECURITY_ADMIN_USER__FILE=/run/secrets/grafana_admin_user
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus

networks:
  caddy:
    name: caddy
    internal: true

volumes:
  grafana:
    name: grafana
  prometheus:
    name: prometheus