x-nc-app: &nc-app
    image: nextcloud:25-apache
    volumes:
        - ncdata:/var/www/html
    networks:
        - nextcloud
        - exposed
    restart: unless-stopped
    links:
        - redis
        - nc-db
    depends_on:
        nc-db:
            condition: service_healthy
        redis:
            condition: service_started
    environment:
        - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
        - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
        - NEXTCLOUD_TRUSTED_DOMAINS=${MY_DOMAIN}
        - NEXTCLOUD_TRUSTED_PROXIES=caddy
        - OVERWRITECLIURL=https://${MY_DOMAIN}
        - OVERWRITEPROTOCOL=https
        - MYSQL_DATABASE_FILE=/run/secrets/mysql_database
        - MYSQL_USER_FILE=/run/secrets/mysql_user
        - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
        - MYSQL_HOST=nc-db
        - REDIS_HOST=redis
    secrets:
        - mysql_user
        - mysql_password
        - mysql_database
        - nextcloud_admin_user
        - nextcloud_admin_password

services:

    nc-db:
        container_name: nc-db
        image: mariadb:10.11.2
        command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
        volumes:
            - ncdb:/var/lib/mysql
        networks:
            - nextcloud
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
            - MYSQL_DATABASE_FILE=/run/secrets/mysql_database
            - MYSQL_USER_FILE=/run/secrets/mysql_user
            - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
            - MARIADB_AUTO_UPGRADE=1
            - MARIADB_DISABLE_UPGRADE_BACKUP=1
        configs:
            - source: mariadb-override
              target: /etc/mysql/conf.d/override.cnf
        secrets:
            - mysql_user
            - mysql_password
            - mysql_database
            - mysql_root_password
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -p$$(cat $$MYSQL_ROOT_PASSWORD_FILE)"]
            interval: 2s
            timeout: 2s
            retries: 120

    redis:
        container_name: redis
        image: redis:7-bullseye
        restart: unless-stopped
        networks:
            - nextcloud

    nc-app:
        container_name: nc-app
        <<: *nc-app
        healthcheck:
            test: curl -sSf 'http://localhost/status.php' | grep '"installed":true' | grep '"maintenance":false' | grep '"needsDbUpgrade":false' || exit 1
            interval: 10s
            timeout: 5s
            retries: 10

    nc-cron:
        container_name: nc-cron
        <<: *nc-app
        entrypoint: /cron.sh
        depends_on:
            nc-app:
                condition: service_healthy

    caddy:
        container_name: caddy
        image: caddy:2.6-alpine
        restart: unless-stopped
        links:
            - nc-app
        ports:
            - 80:80
            - 443:443
        networks:
            - exposed
            - nextcloud
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy-data:/data
            - caddy-config:/config

networks:
    nextcloud:
        name: nextcloud
        internal: true
    exposed:
        name: exposed

volumes:
    ncdata:
        name: ncdata
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /tank/nextcloud/nextcloud_data
    ncdb:
        name: ncdb
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /tank/nextcloud/mariadb
    caddy-data:
        name: caddy-data
    caddy-config:
        name: caddy-config

configs:
    mariadb-override:
        file: ./mariadb_override.cnf

secrets:
    mysql_user:
        file: ../secrets/mysql_user.secret
    mysql_password:
        file: ../secrets/mysql_password.secret
    mysql_database:
        file: ../secrets/mysql_database.secret
    mysql_root_password:
        file: ../secrets/mysql_root_password.secret
    nextcloud_admin_user:
        file: ../secrets/nextcloud_admin_user.secret
    nextcloud_admin_password:
        file: ../secrets/nextcloud_admin_password.secret
