services:

  caddy:
    container_name: caddy
    image: caddy:2.6-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      caddy:
        ipv4_address: 172.30.0.10
      exposed:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config

networks:
  caddy:
    name: caddy
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
  exposed:
    name: exposed

volumes:
  caddy-data:
    name: caddy-data
  caddy-config:
    name: caddy-config
