constants:
  borgbase-testrepo: "{{ secret_from_file['borgbase_repo_address'] }}"

location:
  source_directories:
    - "/mnt/backup/{{ zpool_name }}"

  repositories:
    - path: {borgbase-testrepo}
      label: borgbase_testrepo

storage:
  encryption_passphrase: "{{ secret_from_file['borgbase_repo_passphrase'] }}"

retention:
  keep_daily: 7
  keep_weekly: 5
  keep_monthly: 12
  keep_yearly: 0

consistency:
  checks:
    - name: repository
      frequency: 2 weeks

hooks:
  before_backup:
    - /usr/local/bin/mount-latest-snapshots.sh -m
  after_backup:
    - /usr/local/bin/mount-latest-snapshots.sh -u
  on_error:
    - /usr/local/bin/mount-latest-snapshots.sh -u
