- name: Copy msmtp config file
  ansible.builtin.copy:
    src: "{{ mail_dir }}/msmtprc"
    dest: /etc/msmtprc
    owner: root
    group: root
    mode: '0600'

- name: Copy aliases file
  ansible.builtin.copy:
    src: "{{ mail_dir }}/aliases"
    dest: /etc/aliases
    owner: root
    group: root
    mode: '0600'

