- name: Copy compose file
  ansible.builtin.copy:
    src: "{{ playbook_dir}}/../containers/{{ container_name }}/compose.yaml"
    dest: "{{ container_directory }}/{{ container_name }}/"
    mode: 0644

- name: Copy files from the configuration directory
  ansible.builtin.copy:
    src: "{{ configuration_directory }}"
    dest: "{{ container_directory }}/{{ container_name }}/"
    mode: 0644
  vars:
    - configuration_directory: "{{ playbook_dir}}/../containers/{{ container_name }}/configuration/"
  when: configuration_directory is directory

- name: Template files from the templates directory
  ansible.builtin.template:
    src: "{{ template_file }}"
    dest: "{{ container_directory }}/{{ container_name }}/"
    mode: 0644
  loop: "{{ query('fileglob', templates_directory + '*') + query('fileglob', templates_directory + '.*') }}"
  loop_control:
    loop_var: template_file
  vars:
    - templates_directory: "{{ playbook_dir}}/../containers/{{ container_name }}/templates/"

- name: Unset required secrets
  ansible.builtin.set_fact:
    required_secrets: "{{ [] }}"

- name: Get required secrets
  ansible.builtin.set_fact:
    required_secrets: "{{ lookup('file', required_secrets_file).splitlines() }}"
  when: required_secrets_file is file
  vars:
    - required_secrets_file: "{{ playbook_dir}}/../containers/{{ container_name }}/required_secrets.txt"

- name: Make secrets directory if we have secrets
  ansible.builtin.file:
    path: "{{ container_directory }}/{{ container_name }}/secrets/"
    state: directory
    mode: 0755
  when: required_secrets|length is gt(0)

- name: Copy over required secrets
  ansible.builtin.copy:
    src: "{{ playbook_dir}}/../secrets/{{ secret_name }}.vault"
    dest: "{{ container_directory }}/{{ container_name }}/secrets/{{ secret_name }}"
    mode: 0600
  loop: "{{ required_secrets }}"
  loop_control:
    loop_var: secret_name