- name: Add contrib and backports repositories
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  loop:
    - "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib"
    - "deb-src http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib"

- name: Install some install dependencies
  ansible.builtin.apt:
    update_cache: true
    name:
      - build-essential
      - ca-certificates
      - curl
      - debhelper
      - gnupg

- name: Add docker repo with their sketchy custom script
  block:
    - name: Make sure the key directory exists, as GPG can't create it
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
    - name: Get the docker GPG key
      ansible.builtin.shell:
      args:
        cmd: curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg
        creates: /etc/apt/keyrings/docker.gpg
    - name: Ensure GPG key permissions are correct
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.gpg
        mode: a+r
        state: file
    - name: Add the docker repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        update_cache: true

- name: Install all the packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - borgmatic
      - containerd.io
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - htop
      - libcapture-tiny-perl
      - libconfig-inifiles-perl
      - linux-headers-amd64
      - lzop
      - mailutils
      - mbuffer
      - msmtp-mta
      - pv
      - python3
      - python3-pip
      - rsync
      - zfs-dkms
      - zfsutils-linux
