- name: Checkout sanoid repo
  ansible.builtin.git:
    repo: "https://github.com/jimsalterjrs/sanoid.git"
    dest: "~/sanoid/sanoid"
    version: "v2.2.0"

- name: Link debian folder
  ansible.builtin.file:
    src: "~/sanoid/sanoid/packages/debian"
    dest: "~/sanoid/sanoid/debian"
    state: link

- name: Build sanoid package
  ansible.builtin.command: dpkg-buildpackage -us -uc -b
  args:
    chdir: "~/sanoid/sanoid"
    creates: "~/sanoid/sanoid_2.2.0_all.deb"

- name: Install sanoid package
  ansible.builtin.apt:
    deb: "~/sanoid/sanoid_2.2.0_all.deb"

- name: Copy sanoid config
  ansible.builtin.template:
    src: "{{ sanoid_dir }}/sanoid.template.conf"
    dest: /etc/sanoid/sanoid.conf
    owner: root
    group: root
    mode: '0644'

- name: Copy script for flushing Nextcloud Database
  ansible.builtin.copy:
    src: "{{ sanoid_dir }}/lock-nextcloud-db.sh"
    dest: /usr/local/bin/lock-nextcloud-db.sh
    owner: root
    group: root
    mode: '0744'

- name: Copy sanoid service override
  block:
    - name: Ensure directory exists
      ansible.builtin.file:
        path: "{{ dest_path | dirname }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Copy override.conf
      ansible.builtin.copy:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
        owner: root
        group: root
        mode: '0644'
  vars:
    src_path: "{{ sanoid_dir }}/service.override.conf"
    dest_path: /etc/systemd/system/sanoid.service.d/override.conf

- name: Copy sanoid timer override
  block:
    - name: Ensure directory exists
      ansible.builtin.file:
        path: "{{ dest_path | dirname }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Copy override.conf
      ansible.builtin.copy:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
        owner: root
        group: root
        mode: '0644'
  vars:
    src_path: "{{ sanoid_dir }}/timer.override.conf"
    dest_path: /etc/systemd/system/sanoid.timer.d/override.conf

- name: Copy sanoid timer override
  ansible.builtin.copy:
    src: "{{ sanoid_dir }}/timer.override.conf"
    dest: /etc/systemd/system/sanoid.timer.d/override.conf"
    owner: root
    group: root
    mode: '0644'

- name: Enable sanoid timer
  ansible.builtin.systemd:
    name: sanoid.timer
    enabled: true
    state: started
    daemon_reload: true

