- name: Server setup
  hosts: myservers
  collections:
    - devsec.hardening
  become: true
  roles:
    - role: devsec.hardening.os_hardening
      vars:
        sysctl_overwrite:
          # Enable IP forwarding, required for docker
          net.ipv4.ip_forward: 1
        os_user_pw_ageing: false
        os_rootuser_pw_ageing: false
        os_auth_pam_passwdqc_enable: false
  vars_files:
    - user_variables.yaml
  vars:
    secrets_dir: "{{ playbook_dir }}/../secrets"
    borgbackup_dir: "{{ playbook_dir }}/../borgbackup"
    sanoid_dir: "{{ playbook_dir }}/../sanoid"
    zpool_creation_options: "-o {{ zpool_options | map('quote') | join(' -o ') }} {{ zpool_name | quote }} {{ zpool_raid_type | quote }}"
    dataset_nextcloud_parent_full_name: "{{ zpool_name + '/' + dataset_nextcloud_parent_name }}"
    zfs_create_options_dataset_nextcloud_parent: "{{ dataset_nextcloud_parent_options | map('quote') | map('regex_replace', '^', '-o ') | join(' ') }} {{ dataset_nextcloud_parent_full_name | quote }}"
    dataset_nextcloud_full_name: "{{ dataset_nextcloud_parent_full_name + '/' + dataset_nextcloud_name }}"
    zfs_create_options_dataset_nextcloud: "{{ dataset_nextcloud_options | map('quote') | map('regex_replace', '^', '-o ') | join(' ') }} {{ dataset_nextcloud_full_name | quote }}"
    dataset_db_full_name: "{{ dataset_nextcloud_parent_full_name + '/' + dataset_db_name }}"
    zfs_create_options_dataset_db: "{{ dataset_db_options | map('quote') | map('regex_replace', '^', '-o ') | join(' ') }} {{ dataset_db_full_name | quote }}"
    all_zfs_objects:
      - "{{ zpool_name }}"
      - "{{ dataset_nextcloud_parent_full_name }}"
      - "{{ dataset_nextcloud_full_name }}"
      - "{{ dataset_db_full_name }}"
    secret_files: "{{ query('fileglob', secrets_dir + '/*.secret.vault') }}"
    secret_from_file: "{{ dict(secret_files|map('basename')|map('regex_replace', '^(.*)\\.secret\\.vault$', '\\1') | zip(query('file', *secret_files))) }}"
  tasks:

    - name: Allow memory over commit
      ansible.posix.sysctl:
        name: vm.overcommit_memory
        value: "1"

    - name: Install required things
      include_tasks: install_all_the_things.yaml

    - name: Create/Import zpool and datasets
      include_tasks: setup_zpool.yaml

    - name: Copy container directories and their contents
      include_tasks: copy_container_directory.yaml
      loop:
        - nextcloud
        - monitoring
        - caddy
      loop_control:
        loop_var: container_name

    - name: Install and configure sanoid
      include_tasks: install_configure_sanoid.yaml

    - name: Install and configure borg and borgmatic
      include_tasks: install_configure_borgbackup.yaml

    - name: Start containers
      ansible.builtin.shell: docker compose up -d
      args:
        chdir: "{{ container_directory }}/{{ container_name }}"
      loop:
        - nextcloud
        - monitoring
        - caddy
      loop_control:
        loop_var: container_name

    - name: Secure mariadb container
      include_tasks: secure_mariadb_container.yaml