- name: Server setup
  hosts: myservers
  collections:
    - devsec.hardening
  become: true
  roles:
    - role: devsec.hardening.os_hardening
      vars:
        sysctl_overwrite:
          # Enable IP forwarding, required for docker
          net.ipv4.ip_forward: 1
        os_user_pw_ageing: false
        os_rootuser_pw_ageing: false
        os_auth_pam_passwdqc_enable: false
  vars_files:
    - user_variables.yaml
  vars:
    secrets_dir: "{{ playbook_dir }}/../secrets"
    borgbackup_dir: "{{ playbook_dir }}/../borgbackup"
    sanoid_dir: "{{ playbook_dir }}/../sanoid"
    shell2http_dir: "{{ playbook_dir }}/../shell2http"
    mail_dir: "{{ playbook_dir }}/../mail"
    zpool_creation_options: "-o {{ zpool_options | map('quote') | join(' -o ') }} {{ zpool_name | quote }} {{ zpool_raid_type | quote }}"
    dataset_nextcloud_full_name: "{{ zpool_name + '/' + dataset_nextcloud_name }}"
    dataset_nextcloud_data_full_name: "{{ dataset_nextcloud_full_name + '/' + dataset_nextcloud_data_name }}"
    dataset_nextcloud_db_full_name: "{{ dataset_nextcloud_full_name + '/' + dataset_nextcloud_db_name }}"
    dataset_monitoring_full_name: "{{ zpool_name + '/' + dataset_monitoring_name }}"
    dataset_influxdb_full_name: "{{ dataset_monitoring_full_name + '/' + dataset_influxdb_name }}"
    dataset_loki_full_name: "{{ dataset_monitoring_full_name + '/' + dataset_loki_name }}"
    all_zfs_objects:
      - "{{ zpool_name }}"
      - "{{ dataset_nextcloud_full_name }}"
      - "{{ dataset_nextcloud_data_full_name }}"
      - "{{ dataset_nextcloud_db_full_name }}"
      - "{{ dataset_monitoring_full_name }}"
      - "{{ dataset_influxdb_full_name }}"
      - "{{ dataset_loki_full_name }}"
    required_secrets: "{{ lookup('file', secrets_dir + '/required_secrets.txt').splitlines() }}"
    existing_secret_files: "{{ query('fileglob', secrets_dir + '/*.secret') }}"
    secret_from_file: "{{ dict(existing_secret_files | map('basename') | map('regex_replace', '^(.*)\\.secret$', '\\1') | zip(query('file', *existing_secret_files))) }}"
    missing_secrets: "{{ required_secrets | map('basename') | reject('in', existing_secret_files | map('basename')) }}"
  tasks:

    - name: Abort when secrets are missing
      ansible.builtin.fail:
        msg: "The following secrets are missing from the ./secrets folder: {{ missing_secrets|map('basename')|join(', ') }}"
      when: missing_secrets | length > 0

    - name: Allow memory over commit
      ansible.posix.sysctl:
        name: vm.overcommit_memory
        value: "1"

    - name: Install required things
      include_tasks: install_all_the_things.yaml

    - name: Create/Import zpool
      include_tasks: setup_zpool.yaml

    - name: Create/Import zfs datasets
      include_tasks: setup_zfs_datasets.yaml

    - name: Grab the GID of docker.sock, as it is needed for the monitoring stack
      ansible.builtin.shell: stat -c '%g' /var/run/docker.sock
      register: docker_group_id_command

    - name: Copy container directories and their contents
      include_tasks: copy_container_directory.yaml
      loop:
        - nextcloud
        - monitoring
        - caddy
        - postfix
      loop_control:
        loop_var: container_name

    - name: Install and configure sanoid
      include_tasks: install_configure_sanoid.yaml

    - name: Install and configure borg and borgmatic
      include_tasks: configure_borgbackup.yaml

    - name: Install shell2http for zpool stats
      include_tasks: install_shell2http_for_zpool.yaml

    - name: Configure msmtp on server
      include_tasks: configure_mail.yaml

    - name: Get containers ready to start
      ansible.builtin.shell: docker compose up --no-start --build
      args:
        chdir: "{{ container_directory }}/{{ container_name }}"
      loop:
        - nextcloud
        - monitoring
        - caddy
        - postfix
      loop_control:
        loop_var: container_name

    - name: Secure mariadb container
      include_tasks: secure_mariadb_container.yaml
