- name: Prevent remote root login, remove anonymous users, remove test database, and flush privileges
  ansible.builtin.command: "docker exec nextcloud-db bash -c 'mariadb -u root -p$MYSQL_ROOT_PASSWORD -e \"{{ item }}\"'"
  changed_when: false
  args:
    chdir: "{{ container_directory }}/nextcloud"
  loop:
    - "DELETE FROM mysql.global_priv WHERE User=\\\"root\\\" AND Host NOT IN (\\\"localhost\\\", \\\"127.0.0.1\\\", \\\"::1\\\");"
    - "DELETE FROM mysql.global_priv WHERE User=\\\"\\\";"
    - "DROP DATABASE IF EXISTS test;"
    - "FLUSH PRIVILEGES;"