- name: Check existence of zpool
  ansible.builtin.command: zpool list -H -o name
  register: existing_zpools
  changed_when: false
  check_mode: false

- name: Unknown zpools found
  ansible.builtin.fail:
    msg: "Existing zpool(s) found with name(s): {{ existing_zpools.stdout_lines | join(', ') }}"
  when: existing_zpools.stdout != "" and zpool_name not in existing_zpools.stdout_lines

- name: Import or create zpool
  block:
    - name: Import zpool
      ansible.builtin.command: zpool import -d /dev/disk/by-id/ {{ zpool_name }}
      register: zpool_import_results
      changed_when: false
      ignore_errors: true
    - name: Force import if it failed, and user confirms
      include_tasks: force_import_zpool.yaml
      when: zpool_import_results.rc != 0 and zpool_import_results.stderr_lines.0 is search("pool was previously in use from another system")
    - name: Create zpool as it is not importable
      include_tasks: create_zpool.yaml
      when: zpool_import_results.rc != 0
  when: zpool_name not in existing_zpools.stdout_lines

- name: Enable regular zfs scrub using systemd timer
  ansible.builtin.systemd:
    name: "zfs-scrub-monthly@{{ zpool_name }}.timer"
    enabled: true
    state: started
